//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauDoan.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_detail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order_detail()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public string id { get; set; }
        public string order_id { get; set; }
        public string product_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual Ordertable Ordertable { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
    }
}
