//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MauDoan.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ordertable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ordertable()
        {
            this.Order_detail = new HashSet<Order_detail>();
        }
    
        public string id { get; set; }
        public string user_id { get; set; }
        public Nullable<System.DateTime> order_date { get; set; }
        public Nullable<double> total_amount { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Order_detail> Order_detail { get; set; }
        public virtual Users Users { get; set; }

        //public static implicit operator Ordertable(Ordertable v)
        //{
        //    throw new NotImplementedException();
        //}
    }
}
